### ISSUE TITLE
Running Code with DDP

### ISSUE THREAD

**Issue by Yussef93** [qinenergy/cotta#14]
Hello, I have another inquiry is it possible to run the of semantic segmentation code with DistributedDataParallel option ?

**Comment by qinenergy** [comment]
https://github.com/NVlabs/SegFormer/blob/639caf64aad8241c670c3a6a820ab0a9bde02b77/tools/test.py#L145-L151

I think it should be possible if you modify the function multi_gpu_test accordingly and use the DistributedDataParallel wrapper from above.

However, we didn't test it and will probably not invest time on it. This is because CoTTA is an inference time adaptation method and  inference on multiple gpus may not be realistic in real world applications.
