### ISSUE TITLE
Error in loading ckpt/cifar10/corruptions/Standard.pt

### ISSUE THREAD

**Issue by mohazzam1** [qinenergy/cotta#3]
The error is "_pickle.UnpicklingError: invalid load key, '<'." when `checkpoint = torch.load(model_path, map_location=torch.device('cpu'))`, line 127 in utils.py is executed. The reported size of Standard.pt is 2.2K. Is this file complete?

**Comment by qinenergy** [comment]
Seems to be related to upstream change in Robustbench.  Your downloaded file is incomplete. 

You can refer to https://github.com/wkentaro/gdown/issues/146  https://github.com/RobustBench/robustbench/issues/68

I will try to pull from their fix. Meanwhile, you can directly use the browser to download the files.

**Comment by mohazzam1** [comment]
Got it thanks! I used the browser to download the files

**Comment by qinenergy** [comment]
The downloading function is now updated. https://github.com/qinenergy/cotta/commit/da649b1f26d78b61a01c01e778531ac5838d3336
Thanks for letting us know.

**Comment by ZDstandup** [comment]
Could you tell me how to download Standard.pt by browser?

**Comment by qinenergy** [comment]
You can find all model's google drive id's [here](https://github.com/RobustBench/robustbench/blob/master/robustbench/model_zoo/cifar10.py). 

For the standard.pt for cifar10, the link is https://docs.google.com/uc?export=download&id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC

The auto-downloading script is fixed in April. If you are blocked by GFW, you can use [proxychains](https://github.com/haad/proxychains)

```
conda activate cotta 
CUDA_VISIBLE_DEVICES=0 proxychains python cifar10c.py --cfg cfgs/cifar10/source.yaml
```

**Comment by ZDstandup** [comment]
@qinenergy Thank you a lot for your quick response!
